-- Auto-generated dimension rules by Phase 2.5
-- Generated on: 2025-11-05 22:23:49
-- Database: ecommerce_db

-- Helper functions
function contains(table, element)
    for _, value in pairs(table) do
        if value == element then
            return true
        end
    end
    return false
end

function has_any_field(table_meta, fields)
    if not table_meta.columns then
        return false
    end
    for _, col in pairs(table_meta.columns) do
        if col.name then
            for _, field in ipairs(fields) do
                if col.name == field then
                    return true
                end
            end
        end
    end
    return false
end

-- Dimension detection function
function detect_dimensions(table_name, table_meta)
    local dimensions = {}


    -- Intelligent rules generated by LLM based on Phase 2 analysis

    -- Dynamic rules based on field analysis
    if has_any_field(table_meta, {"price", "sku", "product_id"}) and not contains(table_meta.existing_dimensions, "dim_product") then
        -- Extract column names for attributes
        local column_names = {}
        for _, col in pairs(table_meta.columns) do
            if col.name then
                table.insert(column_names, col.name)
            end
        end
        table.insert(dimensions, {
            name = "dim_product",
            type = "product",
            description = "Product dimension table - automatically identified product-related table",
            source_table = table_name,
            key_fields = {"id"},
            attributes = column_names,
            business_use = "Used for product-related business analysis"
        })
    end

    if has_any_field(table_meta, {"customer_id", "user_id", "email"}) and not contains(table_meta.existing_dimensions, "dim_customer") then
        -- Extract column names for attributes
        local column_names = {}
        for _, col in pairs(table_meta.columns) do
            if col.name then
                table.insert(column_names, col.name)
            end
        end
        table.insert(dimensions, {
            name = "dim_customer",
            type = "people",
            description = "Customer dimension table - automatically identified customer-related table",
            source_table = table_name,
            key_fields = {"id"},
            attributes = column_names,
            business_use = "Used for customer-related business analysis"
        })
    end

    if has_any_field(table_meta, {"created_at", "updated_at", "date"}) and not contains(table_meta.existing_dimensions, "dim_date") then
        -- Extract column names for attributes
        local column_names = {}
        for _, col in pairs(table_meta.columns) do
            if col.name then
                table.insert(column_names, col.name)
            end
        end
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - automatically identified time-related table",
            source_table = table_name,
            key_fields = {"id"},
            attributes = column_names,
            business_use = "Used for time series analysis"
        })
    end

    if has_any_field(table_meta, {"address", "city", "country"}) and not contains(table_meta.existing_dimensions, "dim_location") then
        -- Extract column names for attributes
        local column_names = {}
        for _, col in pairs(table_meta.columns) do
            if col.name then
                table.insert(column_names, col.name)
            end
        end
        table.insert(dimensions, {
            name = "dim_location",
            type = "location",
            description = "Location dimension table - automatically identified geography-related table",
            source_table = table_name,
            key_fields = {"id"},
            attributes = column_names,
            business_use = "Used for geographic location analysis"
        })
    end


    return dimensions
end

-- Fact table detection function
function detect_fact_tables(table_name, table_meta)
    local fact_tables = {}

    -- Rule-based fact table detection
    if has_any_field(table_meta, {"order_id", "quantity", "amount", "total"}) then
        table.insert(fact_tables, {
            name = "fact_sales",
            description = "Sales fact table - records sales transactions",
            source_table = table_name,
            measures = {"quantity", "amount", "total", "discount"},
            dimensions = {"dim_date", "dim_customer", "dim_product", "dim_location"}
        })
    elseif has_any_field(table_meta, {"inventory_change", "stock_quantity"}) then
        table.insert(fact_tables, {
            name = "fact_inventory",
            description = "Inventory fact table - records inventory changes",
            source_table = table_name,
            measures = {"quantity_change", "unit_cost", "total_value"},
            dimensions = {"dim_date", "dim_product", "dim_location"}
        })
    elseif has_any_field(table_meta, {"event_type", "session_id", "page_view"}) then
        table.insert(fact_tables, {
            name = "fact_customer_behavior",
            description = "Customer behavior fact table - records user behavior",
            source_table = table_name,
            measures = {"event_count", "session_duration", "page_views"},
            dimensions = {"dim_date", "dim_customer", "dim_location"}
        })
    end

    return fact_tables
end

return {
    detect_dimensions = detect_dimensions,
    detect_fact_tables = detect_fact_tables
}