-- Auto-generated dimension rules by Phase 2.5
-- Generated on: 2025-11-05 15:11:34
-- Database: ecommerce_db

-- Helper functions
function contains(table, element)
    for _, value in pairs(table) do
        if value == element then
            return true
        end
    end
    return false
end

function has_any_field(table_meta, fields)
    if not table_meta.columns then
        return false
    end
    for _, col in pairs(table_meta.columns) do
        if col.name then
            for _, field in ipairs(fields) do
                if col.name == field then
                    return true
                end
            end
        end
    end
    return false
end

-- Dimension detection function
function detect_dimensions(table_name, table_meta)
    local dimensions = {}


    -- Intelligent rules generated by LLM based on Phase 2 analysis
    if table_name == "shopping_carts" then
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - extracted from shopping cart timestamps",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"expires_at", "created_at", "updated_at"},
            business_use = "Used for shopping cart time series analysis"
        })
    end

    if table_name == "categories" then
        table.insert(dimensions, {
            name = "dim_category",
            type = "product",
            description = "Category dimension table - contains category hierarchy structure",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"name", "description", "parent_id", "sort_order", "is_active"},
            business_use = "Used for category performance analysis and hierarchy statistics"
        })
    end

    if table_name == "customer_addresses" then
        table.insert(dimensions, {
            name = "dim_location",
            type = "location",
            description = "Location dimension table - contains customer address information",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"address_type", "is_default", "street_address", "city", "state", "postal_code", "country"},
            business_use = "Used for geographic analysis and regional sales statistics"
        })
    end

    if table_name == "customers" then
        table.insert(dimensions, {
            name = "dim_customer",
            type = "people",
            description = "Customer dimension table - contains customer information and behavior data",
            source_table = table_name,
            key_fields = {"id", "email"},
            attributes = {"name", "phone", "date_of_birth", "gender", "registration_date", "last_login", "is_active", "customer_type", "total_orders", "total_spent", "loyalty_points"},
            business_use = "Used for customer behavior analysis and segmentation"
        })
    end

    if table_name == "inventory_transactions" then
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - extracted from inventory transaction timestamps",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"created_at"},
            business_use = "Used for inventory time series analysis"
        })
    end

    if table_name == "orders" then
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - extracted from order timestamps",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"created_at", "updated_at", "ordered_at", "confirmed_at", "shipped_at", "delivered_at", "cancelled_at"},
            business_use = "Used for time series analysis and trend analysis"
        })
    end
    if table_name == "orders" then
        table.insert(dimensions, {
            name = "dim_location",
            type = "location",
            description = "Location dimension table - contains address and region information",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"billing_address", "shipping_address"},
            business_use = "Used for geographic analysis and regional sales statistics"
        })
    end

    if table_name == "payments" then
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - extracted from payment timestamps",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"processed_at", "created_at", "updated_at"},
            business_use = "Used for payment time series analysis"
        })
    end

    if table_name == "product_variants" then
        table.insert(dimensions, {
            name = "dim_product",
            type = "product",
            description = "Product dimension table - contains product variant information",
            source_table = table_name,
            key_fields = {"id", "sku"},
            attributes = {"product_id", "name", "price", "cost_price", "compare_at_price", "weight", "dimensions", "inventory_quantity", "option1", "option2", "option3", "is_active"},
            business_use = "Used for product variant analysis and categorization"
        })
    end
    if table_name == "product_variants" then
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - extracted from variant timestamps",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"created_at", "updated_at"},
            business_use = "Used for time series analysis and trend analysis"
        })
    end

    if table_name == "products" then
        table.insert(dimensions, {
            name = "dim_product",
            type = "product",
            description = "Product dimension table - contains product information and attributes",
            source_table = table_name,
            key_fields = {"id", "sku"},
            attributes = {"name", "description", "short_description", "category_id", "price", "cost_price", "compare_at_price", "weight", "dimensions", "inventory_quantity", "inventory_policy", "is_active", "is_featured", "tags", "images", "seo_title", "seo_description"},
            business_use = "Used for product sales analysis and categorization"
        })
    end

    if table_name == "coupons" then
        table.insert(dimensions, {
            name = "dim_promotion",
            type = "event",
            description = "Promotion dimension table - contains coupon and promotion information",
            source_table = table_name,
            key_fields = {"id", "code"},
            attributes = {"name", "description", "discount_type", "discount_value", "minimum_amount", "maximum_discount", "usage_limit", "usage_count", "starts_at", "expires_at", "is_active", "applicable_products", "applicable_categories"},
            business_use = "Used for marketing effectiveness analysis and ROI calculation"
        })
    end
    if table_name == "coupons" then
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - extracted from coupon timestamps",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"starts_at", "expires_at", "created_at", "updated_at"},
            business_use = "Used for time series analysis and trend analysis"
        })
    end

    if table_name == "order_items" then
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - extracted from order item timestamps",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"created_at"},
            business_use = "Used for time series analysis and trend analysis"
        })
    end

    if table_name == "returns" then
        table.insert(dimensions, {
            name = "dim_return",
            type = "event",
            description = "Return dimension table - contains return and refund information",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"reason", "status", "refund_amount", "items", "notes", "requested_at", "approved_at", "received_at", "refunded_at"},
            business_use = "Used for return analysis and quality improvement"
        })
    end
    if table_name == "returns" then
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - extracted from return timestamps",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"requested_at", "approved_at", "received_at", "refunded_at", "created_at", "updated_at"},
            business_use = "Used for time series analysis and trend analysis"
        })
    end

    if table_name == "reviews" then
        table.insert(dimensions, {
            name = "dim_review",
            type = "event",
            description = "Review dimension table - contains user ratings and feedback",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"rating", "title", "content", "images", "is_verified", "helpful_votes", "status"},
            business_use = "Used for rating analysis and user satisfaction research"
        })
    end
    if table_name == "reviews" then
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - extracted from review timestamps",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"created_at", "updated_at"},
            business_use = "Used for time series analysis and trend analysis"
        })
    end

    if table_name == "shipments" then
        table.insert(dimensions, {
            name = "dim_shipment",
            type = "event",
            description = "Shipment dimension table - contains logistics and delivery information",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"tracking_number", "carrier", "status", "shipped_at", "delivered_at", "estimated_delivery", "shipping_address", "weight", "dimensions", "notes"},
            business_use = "Used for logistics analysis and delivery efficiency optimization"
        })
    end
    if table_name == "shipments" then
        table.insert(dimensions, {
            name = "dim_location",
            type = "location",
            description = "Location dimension table - contains shipping address information",
            source_table = table_name,
            key_fields = {"id"},
            attributes = {"shipping_address"},
            business_use = "Used for geographic analysis and regional sales statistics"
        })
    end


    -- Dynamic rules based on field analysis
    if has_any_field(table_meta, {"price", "sku", "product_id"}) and not contains(table_meta.existing_dimensions, "dim_product") then
        -- Extract column names for attributes
        local column_names = {}
        for _, col in pairs(table_meta.columns) do
            if col.name then
                table.insert(column_names, col.name)
            end
        end
        table.insert(dimensions, {
            name = "dim_product",
            type = "product",
            description = "Product dimension table - automatically identified product-related table",
            source_table = table_name,
            key_fields = {"id"},
            attributes = column_names,
            business_use = "Used for product-related business analysis"
        })
    end

    if has_any_field(table_meta, {"customer_id", "user_id", "email"}) and not contains(table_meta.existing_dimensions, "dim_customer") then
        -- Extract column names for attributes
        local column_names = {}
        for _, col in pairs(table_meta.columns) do
            if col.name then
                table.insert(column_names, col.name)
            end
        end
        table.insert(dimensions, {
            name = "dim_customer",
            type = "people",
            description = "Customer dimension table - automatically identified customer-related table",
            source_table = table_name,
            key_fields = {"id"},
            attributes = column_names,
            business_use = "Used for customer-related business analysis"
        })
    end

    if has_any_field(table_meta, {"created_at", "updated_at", "date"}) and not contains(table_meta.existing_dimensions, "dim_date") then
        -- Extract column names for attributes
        local column_names = {}
        for _, col in pairs(table_meta.columns) do
            if col.name then
                table.insert(column_names, col.name)
            end
        end
        table.insert(dimensions, {
            name = "dim_date",
            type = "time",
            description = "Time dimension table - automatically identified time-related table",
            source_table = table_name,
            key_fields = {"id"},
            attributes = column_names,
            business_use = "Used for time series analysis"
        })
    end

    if has_any_field(table_meta, {"address", "city", "country"}) and not contains(table_meta.existing_dimensions, "dim_location") then
        -- Extract column names for attributes
        local column_names = {}
        for _, col in pairs(table_meta.columns) do
            if col.name then
                table.insert(column_names, col.name)
            end
        end
        table.insert(dimensions, {
            name = "dim_location",
            type = "location",
            description = "Location dimension table - automatically identified geography-related table",
            source_table = table_name,
            key_fields = {"id"},
            attributes = column_names,
            business_use = "Used for geographic location analysis"
        })
    end


    return dimensions
end

-- Fact table detection function
function detect_fact_tables(table_name, table_meta)
    local fact_tables = {}

    -- Rule-based fact table detection
    if has_any_field(table_meta, {"order_id", "quantity", "amount", "total"}) then
        table.insert(fact_tables, {
            name = "fact_sales",
            description = "Sales fact table - records sales transactions",
            source_table = table_name,
            measures = {"quantity", "amount", "total", "discount"},
            dimensions = {"dim_date", "dim_customer", "dim_product", "dim_location"}
        })
    elseif has_any_field(table_meta, {"inventory_change", "stock_quantity"}) then
        table.insert(fact_tables, {
            name = "fact_inventory",
            description = "Inventory fact table - records inventory changes",
            source_table = table_name,
            measures = {"quantity_change", "unit_cost", "total_value"},
            dimensions = {"dim_date", "dim_product", "dim_location"}
        })
    elseif has_any_field(table_meta, {"event_type", "session_id", "page_view"}) then
        table.insert(fact_tables, {
            name = "fact_customer_behavior",
            description = "Customer behavior fact table - records user behavior",
            source_table = table_name,
            measures = {"event_count", "session_duration", "page_views"},
            dimensions = {"dim_date", "dim_customer", "dim_location"}
        })
    end

    return fact_tables
end

return {
    detect_dimensions = detect_dimensions,
    detect_fact_tables = detect_fact_tables
}